development:
  adapter: mysql2
  encoding: utf8
  database: hello_backbonejs_development
  pool: 5
  user: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  database: hello_backbonejs_test
  pool: 5
  user: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  database: hello_backbonejs_production
  pool: 5
  user: root
  password:
  socket: /tmp/mysql.sock
